### course create
PUT localhost:8082/course/create
Content-Type: application/json

{
  "name": "Math",
  "price": "140000.0",
  "duration": "12"
}
### course list
GET localhost:8082/course/list
### course get by name
GET localhost:8082/course/get-by-name/Ali
### course get by duration
GET localhost:8082/course/get-by-duration/12
### course get by id
GET localhost:8082/course/get-by-id/1
### course get by price
GET localhost:8082/course/get-by-price/10000
### course get by created date between
GET localhost:8082/course/get-by-between-date
Content-Type: application/json

{
  "start": "",
  "finish": ""
}
### student get by price between
GET localhost:8082/course/get-by-between-price
Content-Type: application/json

{
  "start": "",
  "finish": ""
}
