### Student create
PUT localhost:8082/student/create
Content-Type: application/json

{
  "name": "Muhammad Bilol",
  "surname": "Ahmadjonov",
  "age": "18",
  "gender": "Male",
  "level": "3"
}
### Student list
GET localhost:8082/student/list
### student get by name
GET localhost:8082/student/get-by-name/Raxmonali
### student get by age
GET localhost:8082/student/get-by-age/17
### student get by id
GET localhost:8082/student/get-by-id/1
### student get by level
GET localhost:8082/student/get-by-level/1
### student get by created Date
GET localhost:8082/student/get-by-created-date/
### student get by created date between
GET localhost:8082/student/get-by-between-date
Content-Type: application/json

{
  "start": "",
  "finish": ""
}
### Student pagination
GET http://localhost:8082/student/paging

### Student pagination with name
POST localhost:8082/student/paging-name?page=1&size=6
Content-Type:  application/json

{
  "name": "Ali"
}


### Student paging by given level
GET http://localhost:8082/student/paging-level/1

### Student paging by given gender
GET http://localhost:8082/student/paging-gender/Male

